version: 1

  pre_build:
    - npm install

  # Build command
  build:
    - npm run build

# Specify the directory to deploy
  dir: main

  # Node.js version
  node_version: 14

# Specify the type of project
project_type: node_js
